version: '3'

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - '1433:1433'
      
  web:
    image: contrastsecuritydemo/netflicks:latest
    build: 
      context: .
      dockerfile: Dockerfile.contrast
    depends_on:
      - database
    ports:
      - '8081:80'
    volumes:
      - ./contrast_security.yaml:/etc/contrast/dotnet-core/contrast_security.yaml
    environment:
      - ConnectionStrings__DotNetFlicksConnection=Server=tcp:database,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;
      - CORECLR_PROFILER={8B2CE134-0948-48CA-A4B2-80DDAD9F5791}
      - CORECLR_ENABLE_PROFILING=1
      - CONTRAST_CORECLR_LOGS_DIRECTORY=/opt/contrast/

volumes:
  mysql-data:
