
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -U sa -P reallyStrongPwd123 -Q 'SELECT 1' -b"]
      # test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "http://localhost:1433", "-U", "sa", "-P", "reallyStrongPwd123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


  web-no-contrast:
    image: contrastsecuritydemo/netflicks:latest-no-agent
    build: 
      context: .
      dockerfile: Dockerfile
      target: runtime
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8887:80'
    environment:
      - ConnectionStrings__DotNetFlicksConnection=Server=tcp:database,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;TrustServerCertificate=yes;

  # Development environment for Contrast Assess demos
  web-dev:
    image: contrastsecuritydemo/netflicks:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: runtime-with-contrast
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8888:80'
    volumes:
      - ./contrast_security.yaml:/etc/contrast/dotnet-core/contrast_security.yaml:ro
    environment:
      - ConnectionStrings__DotNetFlicksConnection=Server=tcp:database,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;TrustServerCertificate=yes;
      - CONTRAST__SERVER__NAME=docker-netflicks-dev
      - CONTRAST__SERVER__ENVIRONMENT=development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  web-prod:
    image: contrastsecuritydemo/netflicks:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: runtime-with-contrast
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8889:80'
    volumes:
      - ./contrast_security.yaml:/etc/contrast/dotnet-core/contrast_security.yaml:ro
    environment:
      - ConnectionStrings__DotNetFlicksConnection=Server=tcp:database,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;TrustServerCertificate=yes;
      - CONTRAST__SERVER__NAME=docker-netflicks-prod
      - CONTRAST__SERVER__ENVIRONMENT=production

  # Testing service
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      web-dev:
        condition: service_healthy
    environment:
      - BASEURL=http://web-dev
    profiles:
      - test

volumes:
  mssql-data:
