
services:

  # Development environment for Contrast Assess demos
  web-dev:
    image: "${STAGING_IMAGE_CONTRAST}"

  web-prod:
    image: "${STAGING_IMAGE_CONTRAST}"

  # Testing service
  tests:
    build:
      image: "${STAGING_IMAGE_TESTS}"
