---
apiVersion: v1
kind: Service
metadata:
  name: netflicks-db-service
spec:
  selector:
    app: netflicks-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: netflicks-controller-svc
spec:
  type: LoadBalancer
  selector:
    app: netflicks
  ports:
    - name: "netflicks"
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: netflicks-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netflicks
    spec:
      containers:
      - name: netflicks-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "reallyStrongPwd123"
      - name: netflicks
        image: contrastsecuritydemo/netflicks:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/contrast
          name: contrast-volume
        env:
        - name: CONTRAST__API__API_KEY
          valueFrom:
            secretKeyRef:
              name: contrast
              key: api-key
        - name: CONTRAST__API__SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: contrast
              key: service-key
        - name: CONTRAST__API__URL
          valueFrom:
            secretKeyRef:
              name: contrast
              key: url
        - name: CONTRAST__API__USER_NAME
          valueFrom:
            secretKeyRef:
              name: contrast
              key: user-name
        - name: ConnectionStrings__DotNetFlicksConnection
          value: "Server=tcp:localhost,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;"
      volumes:
      - name: contrast-volume
        emptyDir: {}