pipeline {
    agent any

    options {
        ansiColor('xterm')
    }

    tools {
        terraform 'terraform'
    }

    stages {
        stage('dependencies') {
            steps {
                script {
                    withCredentials([file(credentialsId: env.contrast_yaml, variable: 'path')]) {
                        def contents = readFile(env.path)
                        writeFile file: 'contrast_security.yaml', text: "$contents"
                    }
                }
                sh '''
                (cd terraform && terraform init -upgrade)
                '''
            }
        }
        stage('provision') {
            steps {
                script {
                    withCredentials([azureServicePrincipal('ContrastAzureSponsored')]) {
                        try {
                            sh """
                            export ARM_CLIENT_ID=\$AZURE_CLIENT_ID
                            export ARM_CLIENT_SECRET=\$AZURE_CLIENT_SECRET
                            export ARM_SUBSCRIPTION_ID=\$AZURE_SUBSCRIPTION_ID
                            export ARM_TENANT_ID=\$AZURE_TENANT_ID
                            (cd terraform && terraform apply -auto-approve \
                                -var 'location=$location' \
                                -var 'initials=$initials' \
                                -var 'environment=qa' \
                                -var 'servername=jenkins' \
                                -var 'session_metadata=branchName=qa,committer=James,buildNumber=${env.BUILD_NUMBER}')
                            """
                            FQDN = sh (
                                script: 'cd terraform && terraform output --raw fqdn',
                                returnStdout: true
                            ).trim()
                            echo "FQDN for app is: ${FQDN}"
                        } catch (Exception e) {
                            echo 'Terraform refresh failed, deleting state'
                            sh 'rm -rf terraform/terraform.tfstate'
                            currentBuild.result = 'FAILURE'
                            error('Aborting the build.')
                        }
                    }
                }
            }
        }
        stage('sleeping') {
            steps {
                sleep 120
            }
        }
        stage('exercise - qa') {
            agent { docker { image 'mcr.microsoft.com/playwright/python:v1.32.1-jammy' } }
            steps {
                script {
                    steps {
                        sh 'npm install'
                        sh 'BASEURL=${FQDN} npx playwright@1.32.1 test e2e/assess/*.ts'
                    }
                }
            }
        }
        stage('provision - dev') {
            steps {
                script {
                    withCredentials([azureServicePrincipal('ContrastAzureSponsored')]) {
                        try {
                            sh """
                            export ARM_CLIENT_ID=\$AZURE_CLIENT_ID
                            export ARM_CLIENT_SECRET=\$AZURE_CLIENT_SECRET
                            export ARM_SUBSCRIPTION_ID=\$AZURE_SUBSCRIPTION_ID
                            export ARM_TENANT_ID=\$AZURE_TENANT_ID
                            (cd terraform && terraform apply -auto-approve -var 'location=$location' \
                                -var 'initials=$initials' \
                                -var 'environment=development' \
                                -var 'servername=Macbook-Pro' \
                                -var 'session_metadata=branchName=feat: improved movie search,committer=Mary,buildNumber=${env.BUILD_NUMBER}')
                            """
                        } catch (Exception e) {
                            echo 'Terraform refresh failed, deleting state'
                            sh 'rm -rf terraform/terraform.tfstate'
                            currentBuild.result = 'FAILURE'
                            error('Aborting the build.')
                        }
                    }
                }
            }
        }
        stage('sleeping - dev') {
            steps {
                sleep 120
            }
        }
        stage('exercise - dev') {
            steps {
                script {
                    try {
                        timeout(20) {
                            sh """
                            FQDN=\$(cd terraform && terraform output --raw fqdn)
                            BASEURL=\$FQDN npx playwright@1.32.1 test e2e/assess/*.ts
                            """
                        }
                    } catch (Exception e) {
                        echo 'Exercise stage failed, possible timeout'
                    }
                }
            }
        }
        stage('provision - prod') {
            steps {
                script {
                    withCredentials([azureServicePrincipal('ContrastAzureSponsored')]) {
                        try {
                            sh """
                            export ARM_CLIENT_ID=\$AZURE_CLIENT_ID
                            export ARM_CLIENT_SECRET=\$AZURE_CLIENT_SECRET
                            export ARM_SUBSCRIPTION_ID=\$AZURE_SUBSCRIPTION_ID
                            export ARM_TENANT_ID=\$AZURE_TENANT_ID
                            (cd terraform && terraform apply -auto-approve \
                                -var 'location=$location' \
                                -var 'initials=$initials' \
                                -var 'environment=production' \
                                -var 'servername=Prod-01')
                            """
                        } catch (Exception e) {
                            echo 'Terraform refresh failed, deleting state'
                            sh 'rm -rf terraform/terraform.tfstate'
                            currentBuild.result = 'FAILURE'
                            error('Aborting the build.')
                        }
                    }
                }
            }
        }
        stage('sleeping - prod') {
            steps {
                sleep 120
            }
        }
        stage('attack - prod') {
            steps {
                script {
                    try {
                        timeout(20) {
                            sh """
                            FQDN=\$(cd terraform && terraform output --raw fqdn)
                            BASEURL=\$FQDN npx playwright@1.32.1 test e2e/protect/*.ts
                            """
                        }
                    } catch (Exception e) {
                        echo 'Attack stage failed, possible timeout'
                    }
                }
            }
        }
    }
    post {
        always {
            steps {
                sh "echo 'Cleaning up: Tear down terraform resources'"
                withCredentials([azureServicePrincipal('ContrastAzureSponsored')]) {
                    sh """
                    export ARM_CLIENT_ID=\$AZURE_CLIENT_ID
                    export ARM_CLIENT_SECRET=\$AZURE_CLIENT_SECRET
                    export ARM_SUBSCRIPTION_ID=\$AZURE_SUBSCRIPTION_ID
                    export ARM_TENANT_ID=\$AZURE_TENANT_ID
                    (cd terraform && terraform destroy --auto-approve \
                        -var 'location=$location')
                    """
                }
            }
        }
    }
}
