name: Docker Image CI

on:
  push:
    branches: 
      - main
    tags: 
      - v*
  pull_request:
    branches: 
      - main
  
  workflow_dispatch:
    inputs: 
      contrast_agent_version:
        description: 'Contrast .NET Core agent version to build with'
        required: false
        default: 'latest'

env:
  REGISTRY_IMAGE: contrastsecuritydemo/netflicks

jobs:
  prepare:
    name: Prepare for multi-stage builds
    runs-on: ubuntu-latest
    outputs:
      contrast_version: ${{ steps.versions.outputs.contrast_version }}
    steps:
      - name: Check latest Contrast agent version
        id: versions
        run: |
          docker pull contrast/agent-dotnet-core:${{ github.event.inputs.contrast_agent_version || 'latest' }}
          CONTRAST_VERSION=$(docker image inspect contrast/agent-dotnet-core:latest --format '{{ index .Config.Labels "org.opencontainers.image.version" }}')
          echo "Contrast agent version: ${CONTRAST_VERSION}"
          echo "contrast_version=${CONTRAST_VERSION}" >> $GITHUB_OUTPUT

  #TODO: Add a job to build the base image first
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    needs: 
      - prepare
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      image-name-base: ${{ steps.inspect.outputs['image-name-base'] }}
      image-digest-base: ${{ steps.inspect.outputs['image-digest-base'] }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker daemon for multi-platform builds
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
          annotations: |
            org.opencontainers.image.description=A deliberately vulnerable .NET Core Application for Contrast Security demos
            org.opencontainers.image.vendor=Contrast Security
          tags: |
            type=ref,event=branch,suffix=-base
            type=ref,event=branch,suffix=-base
            type=ref,event=pr,suffix=-base
            type=ref,event=pr,suffix=-base
            
      - name: Build all Docker images for this PR
        id: bake-pr
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file}}
          targets: |
            build
          push: true
          set: |
            *.platform=linux/amd64
            *.platform=linux/arm64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Inspect the created images
        id: inspect
        run: |
          image_name='${{ fromJSON(steps.bake-pr.outputs.metadata).build['image.name'] }}'
          image_digest='${{ fromJSON(steps.bake-pr.outputs.metadata).build['containerimage.digest'] }}'

          echo "Image Name: $image_name"
          echo "Image Digest: $image_digest"
          echo "Image Artifact: $image_name@$image_digest"

          echo "image-name-base=$image_name" >> $GITHUB_OUTPUT
          echo "image-digest-base=$image_digest" >> $GITHUB_OUTPUT
          echo "image-artifact-base=$image_name@$image_digest" >> $GITHUB_OUTPUT

  #TODO: Then share the base image with other jobs via cache

  build:
    name: Build Docker Images
    needs: 
      - prepare
      - build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: runtime
          - name: runtime-with-contrast
          - name: tests
    outputs:
      image-name-runtime: ${{ steps.inspect.outputs['image-name-runtime'] }}
      image-digest-runtime: ${{ steps.inspect.outputs['image-digest-runtime'] }}
      image-artifact-runtime: ${{ steps.inspect.outputs['image-artifact-runtime'] }}
      image-name-runtime-with-contrast: ${{ steps.inspect.outputs['image-name-runtime-with-contrast'] }}
      image-digest-runtime-with-contrast: ${{ steps.inspect.outputs['image-digest-runtime-with-contrast'] }}
      image-artifact-runtime-with-contrast: ${{ steps.inspect.outputs['image-artifact-runtime-with-contrast'] }}
      image-name-tests: ${{ steps.inspect.outputs['image-name-tests'] }}
      image-digest-tests: ${{ steps.inspect.outputs['image-digest-tests'] }}
      image-artifact-tests: ${{ steps.inspect.outputs['image-artifact-tests'] }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker daemon for multi-platform builds
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-from: type=gha,scope=ghcr.io/${{ github.repository }}

      - name: Extract metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
          annotations: |
            org.opencontainers.image.description=A deliberately vulnerable .NET Core Application for Contrast Security demos
            org.opencontainers.image.vendor=Contrast Security
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.image.name }}
            type=ref,event=branch,suffix=-${{ matrix.image.name }}${{ matrix.image.name == 'runtime-with-contrast' && needs.prepare.outputs.contrast_version || null }}
            type=ref,event=pr,suffix=-${{ matrix.image.name }}
            type=ref,event=pr,suffix=-${{ matrix.image.name }}${{ matrix.image.name == 'runtime-with-contrast' && needs.prepare.outputs.contrast_version || null }}
      
      - name: Pull base image
        run: |
          echo "Pulling base image: ${{ needs.build-base.outputs.image-name-base }}"
          docker pull '${{ needs.build-base.outputs.image-name-base }}'

      - name: Build all Docker images for this PR
        id: bake-pr
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file}}
          targets: |
            ${{ matrix.image.name }}
          push: true
          set: |
            *.platform=linux/amd64
            *.platform=linux/arm64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          # *.cache-from=type=registry,ref=${{ needs.build-base.outputs.image-name-base }}
          # *.cache-to=inline

      - name: Inspect the created images
        id: inspect
        run: |
          
          matrix_image_name='${{ matrix.image.name }}'
          echo "Matrix Image Name: $matrix_image_name"
          image_name='${{ fromJSON(steps.bake-pr.outputs.metadata)[matrix.image.name]['image.name'] }}'
          image_digest='${{ fromJSON(steps.bake-pr.outputs.metadata)[matrix.image.name]['containerimage.digest'] }}'

          echo "Image Name: $image_name"
          echo "Image Digest: $image_digest"
          echo "Image Artifact: $image_name@$image_digest"

          echo "image-name-${{ matrix.image.name }}=$image_name" >> $GITHUB_OUTPUT
          echo "image-digest-${{ matrix.image.name }}=$image_digest" >> $GITHUB_OUTPUT
          echo "image-artifact-${{ matrix.image.name }}=$image_name@$image_digest" >> $GITHUB_OUTPUT

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Extract metadata
      #   id: docker-meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: |
      #       - contrastsecuritydemo/netflicks
      #     flavor: |
      #       latest=false
      #     labels: |
      #       org.opencontainers.image.description=A deliberately vulnerable .NET Core Application for Contrast Security demos
      #       org.opencontainers.image.vendor=Contrast Security
      #     tags: |
      #       type=ref,event=branch,suffix=-${{ matrix.image.name }}
      #       type=ref,event=branch,suffix=-${{ matrix.image.name }}${{ matrix.image.name == 'runtime-with-contrast' && needs.prepare.outputs.contrast_version || null }}
      #       type=ref,event=pr,suffix=-${{ matrix.image.name }}
      #       type=ref,event=pr,suffix=-${{ matrix.image.name }}${{ matrix.image.name == 'runtime-with-contrast' && needs.prepare.outputs.contrast_version || null }}
      #       type=semver,pattern={{version}},prefix=contrast,value=${{ needs.prepare.outputs.contrast_version }},enable=${{ matrix.image.name == 'runtime-with-contrast' }}
      #       type=semver,pattern={{major}}.{{minor}},prefix=contrast,value=${{ needs.prepare.outputs.contrast_version }},enable=${{ matrix.image.name == 'runtime-with-contrast' }}
      #       type=semver,pattern={{major}},prefix=contrast,value=${{ needs.prepare.outputs.contrast_version }},enable=${{ matrix.image.name == 'runtime-with-contrast' }}
      #       type=raw,value=${{ matrix.image.name == 'runtime-with-contrast' && 'latest-contrast' || 'latest' }},enable={{is_default_branch}}

  test: 
    name: Test Docker Images
    needs: 
      - build
    runs-on: ubuntu-latest
    env: 
      STAGING_IMAGE_RUNTIME: ${{ needs.build.outputs.image-name-runtime }}
      STAGING_IMAGE_RUNTIME_WITH_CONTRAST: ${{ needs.build.outputs.image-name-runtime-with-contrast }}
      STAGING_IMAGE_TESTS: ${{ needs.build.outputs.image-name-tests }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Pull the staging docker images
        run: |
          echo "STAGING_IMAGE_RUNTIME=$STAGING_IMAGE_RUNTIME" > .env
          echo "STAGING_IMAGE_RUNTIME_WITH_CONTRAST=$STAGING_IMAGE_RUNTIME_WITH_CONTRAST" >> .env
          echo "STAGING_IMAGE_TESTS=$STAGING_IMAGE_TESTS" >> .env

          docker compose pull 

      - name: Run e2e tests with Playwright
        run: |
          echo "Running tests for the Docker images..."
          docker compose -f docker-compose.yml -f docker-compose.ci.yml --profile tests up --abort-on-container-exit --exit-code-from tests

      - name: Save Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report
          retention-days: 7
