name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v4
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with: 
          push: false
          load: true
          tags: contrastsecuritydemo/netflicks:latest-agent
  
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - 
        run: |
          echo Testing now
      -
        name: Checkout branch
        uses: actions/checkout@v4
      -
        name: Run docker-compose tests
        run: | 
          docker-compose up -d 
      - 
        name: Setup Node
        uses: actions/setup-node@v3
      - 
        name: Install dependencies
        run: | 
          cd e2e
          npm install
          npx playwright install
      - 
        name: Install playwright browsers
        run: |
          cd e2e
          npx playwright install-deps chromium
      - 
        name: Run tests
        run: |
          cd e2e
          npx playwright test

  merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs: 
      - build
      - test

    steps:
      - run: |
          echo The PR was merged
