name: Docker Image CI

on:
  push:
    branches: 
      - main
    tags: 
      - v*
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    inputs: 
      contrast_agent_version:
        description: 'Contrast .NET Core agent version to build with'
        required: false
        default: 'latest'

env:
  REGISTRY_IMAGE: contrastsecuritydemo/netflicks

jobs:
  prepare:
    name: Prepare for multi-stage builds
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Rename meta bake definition file
        run: |
          mv "${{ steps.meta.outputs.bake-file }}" "${{ runner.temp }}/bake-meta.json"
          echo ${{ runner.temp }}/bake-meta.json

      - name: Upload meta bake definition
        uses: actions/upload-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}/bake-meta.json
          if-no-files-found: error
          retention-days: 1
       
  build:
    name: Build Multi-Stage Docker Images
    needs: 
      - prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: runtime
          - name: runtime-with-contrast
          - name: tests
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Download meta bake definition
        uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}
      
      - name: Set up Docker daemon for multi-platform builds
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            - contrastsecuritydemo/netflicks
          flavor: |
            latest=true
            suffix=${{ matrix.image.name == 'runtime-with-contrast' && '-contrast' || null }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      # Need to do two bake steps because load=true is not compatible with push-by-digest=true
      # https://github.com/moby/buildkit/issues/5556
      - name: Build all Docker images for this PR
        id: bake-pr
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
          targets: |
            ${{ matrix.image.name }}
          push: false
          load: true
          set: |
            *.platform=linux/amd64
            *.platform=linux/arm64
 
      # - name: Run docker-compose tests
      #   run: | 
      #     docker compose --profile tests up --abort-on-container-exit --exit-code-from tests 

      # - name: Get currently installed Contrast agent version
      #   id: versions
      #   run: | 
      #     docker compose up web-dev -d
      #     docker compose cp web-dev:/opt/contrast/image-manifest.json image-manifest.json
      #     CONTRAST_VERSION=$(cat image-manifest.json | jq -r '.version')
      #     echo "contrast_version=${CONTRAST_VERSION}" >> $GITHUB_OUTPUT
      #     docker compose down
      #     echo "Contrast agent version: ${CONTRAST_VERSION}"

      - name: Inspect the created images
        run: | 
          docker image ls -a 
        
      # docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.tags }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

